# Default configuration for the Etsy keyword discovery pipeline
runtime:
  geo: "US"
  discovery_budget: 3000
  pages_to_sample: 2
  min_results: 200
  max_results: 20000
  sleep_min_ms: 2000
  sleep_max_ms: 7000
  concurrency: 2

weights:
  review_velocity: 1.0
  favorites: 0.5
  ad_ratio: 0.8
  dominance: 0.7
  price_dispersion: 0.4

playwright:
  headless: true
  proxy:
    enabled: false
    url: ""
    username: ""
    password: ""
  user_agents:
    - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36"
    - "Mozilla/5.0 (Macintosh; Intel Mac OS X 13_3) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.4 Safari/605.1.15"

paths:
  data_dir: "./data"
  outputs_dir: "./outputs"
  db_file: "./data/cache.db"

logging:
  level: "info"
  format: "json"
